### ISSUE TITLE
Can you port this player to real hardware(Genesis/Megadrive)?

### ISSUE THREAD

**Issue by 110-kenichi** [ValleyBell/SMPSPlay#13]
Can you port this player to the real hardware(Genesis/Megadrive)?

We need to sound psz files on the real hardware(Genesis/Megadrive) for our development game.
Could you please help?

VGM/XGM file size is too big to sound on the reak hardware...

**Comment by 110-kenichi** [comment]
If I rewrite Z80Drv.bin, Z80DACDrv?.bin to Z80 memory, I can play the psz file on the real hardware?

**Comment by ValleyBell** [comment]
Porting SMPSPlay to the MegaDrive would be a huge amount of work. It is not something I will do by myself.

With "psz" files you probably refer to preSMPS Z80 drivers.
You can try to write Z80Drv.bin to Z80 memory, starting at address 0. However you will have to patch the driver so that it sets the Z80 ROM bank to the correct location, which is hardcoded into the driver.
Alternatively you place the 32 KB ROM bank that contains the songs (called "Driver Bank" in Pointers.txt) at the same spot in your custom ROM as it was in the original game.

Also, keep in mind that every preSMPS Z80 driver comes with its own oddities, so you can not use the driver from game A to play songs from game B.
The file extension only serves as a rough categorisation of the underlying SMPS format.

**Comment by 110-kenichi** [comment]
Thank you for your detailed information ! I understood roughly.
We will "upgrade" the existing genesis game. But musics are re-used.
